apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}
spec:
  ports:
    - name: web
      protocol: TCP
      port: 8888
      targetPort: 8888
    - name: rpc
      protocol: TCP
      port: 8889
      targetPort: 8889
  selector:
    app: {{ .Chart.Name }}
    release: {{ .Release.Name }}
  type: ClusterIP