name: CI - build 

on:
  push:
    branches: 
      - "master"

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repo
      uses: actions/checkout@v3

    - name: Set variables
      id: variables
      run: |
        REF=$(git rev-parse --short "$GITHUB_SHA")

        echo "branch=${{ github.ref_name }}" >> $GITHUB_OUTPUT
        echo "ref=$REF" >> $GITHUB_OUTPUT

    - name: Login to Docker
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_HUB_USERNAME }}
        password: ${{ secrets.DOCKER_HUB_PASSWORD }}

    - name: Build and push
      uses: docker/build-push-action@v3
      with:
        push: true
        tags: |
          ovatu/redalert:latest
          ovatu/redalert:${{ steps.variables.outputs.ref }}